### ISSUE TITLE
Templating options

### ISSUE THREAD

**Issue by claesnn** [samuelcolvin/FastUI#43]
Great project!

Would it be possible to enable templating in JSX? The upside is potentially easier integration into JavaScript modules and I also find the code simpler to view.

**Comment by samuelcolvin** [comment]
I'm not sure what you mean?

**Comment by claesnn** [comment]
It's very likely outside the scope of the project. But I'd find it interesting if it's possible to use JavaScript XML for writing templates, like Jinja2 for Django/Flask.

So instead of 

`        c.Page(  # Page provides a basic container for components
            components=[
                c.Heading(text='Users', level=2),  # renders `<h2>Users</h2>`
                c.Table[User](  # c.Table is a generic component parameterized with the model used for rows
                    data=users,
                    # define two columns for the table
                    columns=[
                        # the first is the users, name rendered as a link to their profile
                        DisplayLookup(field='name', on_click=GoToEvent(url='/user/{id}/')),
                        # the second is the date of birth, rendered as a date
                        DisplayLookup(field='dob', mode=DisplayMode.date),
                    ],
                ),
            ]
        ),`

Maybe one could use the following syntax (of course as long as data can be forwarded from FastAPI to the React part).

`
<main>
  <h2>Users</h2>
  <table data={users} columns={columns} />
</main>
`

It's likely not a simple solution, as I guess one would have to ideally hook into react-router-dom to map FastAPI routes to UI routes.

**Comment by samuelcolvin** [comment]
ye, I think that's beyond the bounds of what FastUI is trying to do right now.

**Comment by hasansezertasan** [comment]
@claesnn As far as I know, [reactive-python/reactpy: It's React, but in Python](https://github.com/reactive-python/reactpy) does something similar to what you want.
