### ISSUE TITLE
Difference from Gradio

### ISSUE THREAD

**Issue by fakerybakery** [samuelcolvin/FastUI#69]
Hi, great library. Just wondering how this is different from Gradio

**Comment by samuelcolvin** [comment]
No idea, never used gradio. Would be great if someone could tell us though...?

**Comment by Zaubeerer** [comment]
https://www.gradio.app/guides/quickstart seems similar to https://streamlit.io/: "define data/web app in python script"

So, I guess that a development flow could be as follows:
1. Prototype with streamlit or gradio or similar
2. When streamlit/gradio are limiting: 
   I. Implement FastAPI as backend for the frontend
   II. Implement more tailored frontend with FastUI

Until FastUI gets simple & powerful enough that one directly starts with FastUI & FastAPI (e.g. have a FastUI-Streamlit template repo that looks similar to streamlit and is almost as easy to use as writing a python script) :)

**Comment by samuelcolvin** [comment]
Makes sense, my guess is we can make FastUI easy enough to use that it works from day one.

**Comment by hasansezertasan** [comment]
@fakerybakery GradIO is simply "IO" based User Interface technology, it's quite limited if you want to build large applications.

GradIO performs communication between backend and frontend via websocket but FastUI doesn't do that. Think of it like GradIO is a "drag and drop UI builder with tons of limitations" and FastUI is a (almost) fully fledged UI Framework.

On the other hand, GradIO has it's own syntax and pattern to build interfaces, it's not easy (or possible) to build routes with custom forms/elements but you can use FastUI to implement routes with different components, elements, forms.

Major downside of GradIO is using websocket to communicate with backend and interface limitations. I think the answer to your question is similar to @samuelcolvin's answer on #67. We can not (you can but doesn't makes sense) compare sandwiches with Tesla Model X

**Comment by fakerybakery** [comment]
Thank you for your detailed explanation! That makes sense. So basically Gradio is a more basic framework for making simple webapps and FastUI is for making production-ready more complex apps?

**Comment by skullcrash** [comment]
What about 'Reflex' ? [reflex.dev](https://reflex.dev)
What are the differences with FastUI ?

**Comment by hasansezertasan** [comment]
> What about 'Reflex' ? [reflex.dev](https://reflex.dev)
> What are the differences with FastUI ?

Well, reflex is quite different. It has a lot abstraction over routing and database. The communication between frontend and backend accomplished via websockets (like NiceGUI,liveview approach).

**Comment by hasansezertasan** [comment]
> What about 'Reflex' ? [reflex.dev](https://reflex.dev)
> What are the differences with FastUI ?

Reflex and NiceGUI is quite different from FastUI.

Reflex and NiceGUI automatically handles routing and communication between frontend and backend via websockets (similar to liveview). You don't need to think about routing.

With FastUI, it's your job to think about it, you need to write the routes and do the connections (tell your application when this happens, navigate to the x path) by yourself.

Also, reflex has its own ORM abstraction over the SQLAlchemy.

They all use some JacaScript frontend framework.

Edit: I did look at the source code of all these packages. I am planning to write some stuff about it in the future.

**Comment by skullcrash** [comment]
Reflex is using FastApi and SQLModel underneath.
PyScript is also interesting.
All these python initiatives are very different and indeed it it not easy to catch the differences sometimes.

**Comment by hasansezertasan** [comment]
> Reflex is using FastApi and SQLModel underneath.
> PyScript is also interesting.
> All these python initiatives are very different and indeed it it not easy to catch the differences sometimes.

NiceGUI also uses FastAPI as its backend core. One other downside of reflex is its dependencies, its too many! It requires starlette-admin (awesome package, check it out) but ı checked the source code. It doesn't do anything with it (I might be missing something, let me know if I am).

**Comment by hasansezertasan** [comment]
> Reflex is using FastApi and SQLModel underneath.
> PyScript is also interesting.
> All these python initiatives are very different and indeed it it not easy to catch the differences sometimes.

NiceGUI also uses FastAPI as its backend core. One other downside of reflex is its dependencies, its too many and versions are so strict.

WASM is not there yet and I think it won't be in the near future (I am talking about small size applications).

FastUIs approach is not quite new. Check aout baidu/amis and json schema form builders (there are many implementations but I do recommend checking json-editor). These technologies depends on backend to build the UI in a JSON based specs.
